on:
  push:
    branches:
      - main
    paths:
      - 2[0-9]+/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-24.04
    steps:
      - name: cache downloaded APT packages
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/deb
          key: fastq-concat-expr/plot
      - name: install APT packages needed
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: sudo apt-get install -y r-cran-data.table r-cran-lubridate r-cran-ggplot2 r-cran-svglite
      - name: backup downloaded DEB package files
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          set -euo pipefail
          mkdir /tmp/deb/
          cp -aiR /var/cache/apt/archives/*.deb /tmp/deb/
      - name: install restored DEB package files
        if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: sudo dpkg --install /tmp/deb/*.deb

      - uses: actions/checkout@v4.1.7
      - name: generating plots...
        run: |
          for i in 2???????; do \
            cd $i; mkdir -p plots; ./plots.R; \
            cd ..; \
          done
      - run: ls -l 2???????/plots
      - name: push new plots to github
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@noreply.github.com"
          git add 2???????/plots
          git commit -m "generated plots"
          git push

#end
